# Generated by Django 5.2.11 on 2026-02-25 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DailyPriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("site", models.CharField(max_length=50)),
                ("product_name", models.CharField(max_length=500)),
                ("price", models.PositiveIntegerField()),
                ("url", models.URLField(max_length=1000)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="price.keyword",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "price"],
                "indexes": [
                    models.Index(
                        fields=["keyword", "date"],
                        name="price_daily_keyword_859ed3_idx",
                    )
                ],
            },
        ),
    ]
