# Generated by Django 6.0.2 on 2026-02-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='min_price',
            field=models.PositiveIntegerField(default=20000, help_text='Only save prices >= this (JPY)'),
        ),
    ]
