# Generated by Django 6.0.2 on 2026-03-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_delete_hardwaretierrow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailypricesummary',
            name='unique_keyword_date_site_summary',
        ),
        migrations.RenameIndex(
            model_name='dailypricesnapshot',
            new_name='price_daily_keyword_a10b41_idx',
            old_name='price_daily_keyword_ki_idx',
        ),
        migrations.RenameIndex(
            model_name='dailypricesummary',
            new_name='price_daily_keyword_6e7063_idx',
            old_name='price_summary_kw_date_idx',
        ),
        migrations.RenameIndex(
            model_name='dailypricesummary',
            new_name='price_daily_categor_70e506_idx',
            old_name='price_summary_cat_date_idx',
        ),
        migrations.AlterField(
            model_name='dailypricesnapshot',
            name='category',
            field=models.CharField(blank=True, choices=[('gpu', 'GPU'), ('cpu', 'CPU'), ('motherboard', 'Motherboard'), ('ram', 'RAM'), ('ssd', 'SSD'), ('custom', '自定义')], db_index=True, default='gpu', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailypricesummary',
            name='category',
            field=models.CharField(blank=True, choices=[('gpu', 'GPU'), ('cpu', 'CPU'), ('motherboard', 'Motherboard'), ('ram', 'RAM'), ('ssd', 'SSD'), ('custom', '自定义')], db_index=True, default='gpu', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='category',
            field=models.CharField(choices=[('gpu', 'GPU'), ('cpu', 'CPU'), ('motherboard', 'Motherboard'), ('ram', 'RAM'), ('ssd', 'SSD'), ('custom', '自定义')], db_index=True, default='gpu', help_text='Hardware category for filtering and display', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='dailypricesummary',
            unique_together={('keyword', 'date', 'site')},
        ),
    ]
