# Generated by Django 5.2.17 on 2026-09-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0010_set_keyword_guide_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='jd_price_cny',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='京东参考价，人工维护 (CNY)', max_digits=10, null=True),
        ),
    ]
